name: user_activity_logger
description: A small and practical Dart-only Flutter package to log simple user activities.
version: 0.0.1
homepage: https://github.com/yourusername/user_activity_logger
repository: https://github.com/yourusername/user_activity_logger
issue_tracker: https://github.com/yourusername/user_activity_logger/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0

flutter: